#!/bin/bash
# chkconfig: 345 88 08
# description: Forever for Node.js

WORKDIR=/home/node/WSFrameWork.nodejs/cancer/www/cancer_www
DEAMON=/home/node/WSFrameWork.nodejs/cancer/www/cancer_www/bin/www
LOG=/home/node/WSFrameWork.nodejs/cancer/www/cancer_www/log/forever.log
PID=/root/.forever/pids/forever.pid

#export PATH=$PATH:/usr/bin/node/bin
export NODE_PATH=$NODE_PATH:/usr/lib/node_modules

node=node
forever=forever

case "$1" in
    start)
        $forever start --workingDir $WORKDIR  -l $LOG --pidFile $PID -a $DEAMON
        ;;
    stop)
        $forever stop --pidFile $PID $DEAMON
        ;;
    stopall)
        $forever stopall --pidFile $PID
        ;;
    restartall)
        $forever restartall --pidFile $PID
        ;;
    reload|restart)
        $forever restart -l $LOG --pidFile $PID -a $DEAMON
        ;;
    list)
        $forever list
        ;;
    *)
        echo "Usage: /etc.init.d/node {start|stop|restart|reload|stopall|restartall|list}"
        exit 1
        ;;
esac

